model_name_or_path: /root/autodl-tmp/workspace/MMLA/models/Qwen2-VL-7B-Instruct
stage: sft
do_train: true

finetuning_type: lora
lora_target: all

dataset_dir: /root/autodl-tmp/workspace/MMLA/src/Frameworks/LLaMA-Factory-main/data
dataset: IT_all9_train_llamafactory
eval_dataset: IT_all9_dev_llamafactory

template: qwen2_vl
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 2

output_dir: /root/autodl-tmp/workspace/MMLA/outputs/it/all9/Qwen2-VL-7B-Instruct
logging_steps: 20
save_steps: 500
plot_loss: true
overwrite_output_dir: true
compute_accuracy: false

per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
